import Image from "next/image";
import Link from "next/link";
import { PortableText, type PortableTextComponents } from "@portabletext/react";
import type { PortableTextBlock } from "next-sanity";
import { buildHeadingIds } from "@/lib/posts";
import { urlForImage } from "@/sanity/lib/image";

/**
 * Renders a post body.
 *
 * This is the replacement for the MDX pipeline, and it deliberately emits the
 * same bare HTML that remark-gfm + rehype-slug did: headings, paragraphs,
 * lists, tables and blockquotes as direct siblings with no wrapper elements.
 * `.prose-paper` in globals.css styles by element and relies on that - most
 * sharply in `.prose-paper h2#tldr + p`, which only works while the TL;DR
 * heading and its paragraph remain adjacent siblings.
 *
 * Heading IDs come from the shared map in lib/posts so the table of contents
 * and the anchors it points at are generated by the same pass.
 */

type Props = { value: PortableTextBlock[] };

function buildComponents(ids: Map<string, string>): PortableTextComponents {
  const headingId = (value: unknown): string | undefined => {
    const key = (value as { _key?: string })?._key;
    return key ? ids.get(key) : undefined;
  };

  return {
    block: {
      normal: ({ children }) => <p>{children}</p>,
      h2: ({ children, value }) => <h2 id={headingId(value)}>{children}</h2>,
      h3: ({ children, value }) => <h3 id={headingId(value)}>{children}</h3>,
      h4: ({ children, value }) => <h4 id={headingId(value)}>{children}</h4>,
      // The inner <p> is not decorative: remark-gfm emitted one, and
      // `.prose-paper p` is what gives a quote its bottom spacing. Without it
      // every blockquote on the site tightens by 1.25rem.
      blockquote: ({ children }) => (
        <blockquote>
          <p>{children}</p>
        </blockquote>
      ),
    },

    list: {
      bullet: ({ children }) => <ul>{children}</ul>,
      number: ({ children }) => <ol>{children}</ol>,
    },

    listItem: {
      bullet: ({ children }) => <li>{children}</li>,
      number: ({ children }) => <li>{children}</li>,
    },

    marks: {
      strong: ({ children }) => <strong>{children}</strong>,
      em: ({ children }) => <em>{children}</em>,
      code: ({ children }) => <code>{children}</code>,
      "strike-through": ({ children }) => <s>{children}</s>,
      link: ({ children, value }) => {
        const href = (value as { href?: string })?.href ?? "#";
        // Internal paths go through next/link for client-side navigation.
        // Both branches emit a plain <a href>, which is what the MDX build
        // produced and what .prose-paper styles.
        if (href.startsWith("/")) return <Link href={href}>{children}</Link>;
        return <a href={href}>{children}</a>;
      },
    },

    types: {
      image: ({ value }) => {
        const source = value as { alt?: string; caption?: string; asset?: { _ref?: string } };
        if (!source?.asset?._ref) return null;
        const url = urlForImage(value as never).width(1600).url();
        return (
          <figure className="my-10">
            <Image
              src={url}
              alt={source.alt ?? ""}
              width={1600}
              height={900}
              sizes="(min-width: 1024px) 720px, 100vw"
              className="h-auto w-full rounded-xl"
            />
            {source.caption ? (
              <figcaption className="mt-3 text-sm text-[color:var(--color-ink-2)]/70">
                {source.caption}
              </figcaption>
            ) : null}
          </figure>
        );
      },

      divider: () => <hr />,

      codeBlock: ({ value }) => {
        const code = (value as { code?: string })?.code ?? "";
        const language = (value as { language?: string })?.language;
        return (
          <pre className="my-8 overflow-x-auto rounded-xl bg-[color:var(--color-charcoal)] p-5 text-sm text-[color:var(--color-glacier)]">
            <code data-language={language}>{code}</code>
          </pre>
        );
      },

      callout: ({ value }) => {
        const tone = (value as { tone?: string })?.tone ?? "note";
        const text = (value as { text?: PortableTextBlock[] })?.text ?? [];
        return (
          <aside data-tone={tone} className="callout-paper">
            <PortableText value={text} components={{ block: { normal: ({ children }) => <p>{children}</p> } }} />
          </aside>
        );
      },

      table: ({ value }) => {
        const v = value as { caption?: string; header?: string[]; rows?: { cells?: string[] }[] };
        const header = v.header ?? [];
        const rows = v.rows ?? [];
        // Emitted bare, exactly as remark-gfm did, so .prose-paper's table
        // rules and the surrounding sibling spacing are unchanged.
        return (
          <table>
            {v.caption ? <caption className="sr-only">{v.caption}</caption> : null}
            <thead>
              <tr>
                {header.map((cell, i) => (
                  <th key={i}>{cell}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((row, r) => (
                <tr key={r}>
                  {(row.cells ?? []).map((cell, c) => (
                    <td key={c}>{cell}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        );
      },
    },

    hardBreak: () => <br />,
  };
}

export function PortableTextBody({ value }: Props) {
  const ids = buildHeadingIds(value);
  return <PortableText value={value} components={buildComponents(ids)} />;
}
